site_name: QubesOS 3mdeb minisummit
site_url: https://qubesos.3mdeb.com
theme:
    name: material
    favicon: images/qubes-logo.png
    logo: images/qubes-logo.png
extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/3mdeb_com
          name: 3mdeb on Twitter
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - attr_list
    - meta
    - tables
    - pymdownx.tasklist:
          custom_checkbox: true
plugins: []
