name: deploy mkdocs
on:
  push:
    branches:
      - master
      - main
      - mkdocs
      - qubes-main-page
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: ls
      - run: mkdocs gh-deploy --force
